# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170215_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsignup',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='member',
        ),
        migrations.RemoveField(
            model_name='event',
            name='member_signup',
        ),
        migrations.DeleteModel(
            name='EventSignup',
        ),
    ]
