# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_club'),
        ('events', '0003_auto_20170222_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('start_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='member_signup',
            field=models.ManyToManyField(through='events.EventSignup', to='members.Member'),
        ),
    ]
