# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170222_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='signup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
