# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_official', '0002_auto_20170214_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
