# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_club'),
        ('courses', '0004_remove_course_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(to='members.Member'),
        ),
    ]
