# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170305_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperworkTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperwork', models.FileField(upload_to='paperwork_templates')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursetype',
            name='paperwork_template',
        ),
        migrations.AddField(
            model_name='paperworktemplates',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseType'),
        ),
    ]
