# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170222_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsignup',
            name='date',
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='signup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
